//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/pinchAndroid.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PinchAndroid : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PinchAndroid()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""pinchAndroid"",
    ""maps"": [
        {
            ""name"": ""Android"",
            ""id"": ""55ed85a7-cfce-4142-b681-582b9b308777"",
            ""actions"": [
                {
                    ""name"": ""FirstFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""530231a9-3781-42f5-9aaa-92991213e4b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""3176c7a3-fa1c-4475-9fcc-1b1b39b9aa54"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondTouchContact"",
                    ""type"": ""Button"",
                    ""id"": ""c5f3cf17-5dcb-4eb8-88b3-a08789fce295"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ace17d7b-8dc1-4638-94a8-99a3c7741917"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PinchSystem"",
                    ""action"": ""FirstFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6beaa0a8-2a0d-41e7-892c-c0c6e0d4d901"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PinchSystem"",
                    ""action"": ""SecondFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42570808-7214-4e20-8299-6e41e3410e3d"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PinchSystem"",
                    ""action"": ""SecondTouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PinchSystem"",
            ""bindingGroup"": ""PinchSystem"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Android
        m_Android = asset.FindActionMap("Android", throwIfNotFound: true);
        m_Android_FirstFingerPosition = m_Android.FindAction("FirstFingerPosition", throwIfNotFound: true);
        m_Android_SecondFingerPosition = m_Android.FindAction("SecondFingerPosition", throwIfNotFound: true);
        m_Android_SecondTouchContact = m_Android.FindAction("SecondTouchContact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Android
    private readonly InputActionMap m_Android;
    private IAndroidActions m_AndroidActionsCallbackInterface;
    private readonly InputAction m_Android_FirstFingerPosition;
    private readonly InputAction m_Android_SecondFingerPosition;
    private readonly InputAction m_Android_SecondTouchContact;
    public struct AndroidActions
    {
        private @PinchAndroid m_Wrapper;
        public AndroidActions(@PinchAndroid wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstFingerPosition => m_Wrapper.m_Android_FirstFingerPosition;
        public InputAction @SecondFingerPosition => m_Wrapper.m_Android_SecondFingerPosition;
        public InputAction @SecondTouchContact => m_Wrapper.m_Android_SecondTouchContact;
        public InputActionMap Get() { return m_Wrapper.m_Android; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AndroidActions set) { return set.Get(); }
        public void SetCallbacks(IAndroidActions instance)
        {
            if (m_Wrapper.m_AndroidActionsCallbackInterface != null)
            {
                @FirstFingerPosition.started -= m_Wrapper.m_AndroidActionsCallbackInterface.OnFirstFingerPosition;
                @FirstFingerPosition.performed -= m_Wrapper.m_AndroidActionsCallbackInterface.OnFirstFingerPosition;
                @FirstFingerPosition.canceled -= m_Wrapper.m_AndroidActionsCallbackInterface.OnFirstFingerPosition;
                @SecondFingerPosition.started -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.performed -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.canceled -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondFingerPosition;
                @SecondTouchContact.started -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondTouchContact;
                @SecondTouchContact.performed -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondTouchContact;
                @SecondTouchContact.canceled -= m_Wrapper.m_AndroidActionsCallbackInterface.OnSecondTouchContact;
            }
            m_Wrapper.m_AndroidActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstFingerPosition.started += instance.OnFirstFingerPosition;
                @FirstFingerPosition.performed += instance.OnFirstFingerPosition;
                @FirstFingerPosition.canceled += instance.OnFirstFingerPosition;
                @SecondFingerPosition.started += instance.OnSecondFingerPosition;
                @SecondFingerPosition.performed += instance.OnSecondFingerPosition;
                @SecondFingerPosition.canceled += instance.OnSecondFingerPosition;
                @SecondTouchContact.started += instance.OnSecondTouchContact;
                @SecondTouchContact.performed += instance.OnSecondTouchContact;
                @SecondTouchContact.canceled += instance.OnSecondTouchContact;
            }
        }
    }
    public AndroidActions @Android => new AndroidActions(this);
    private int m_PinchSystemSchemeIndex = -1;
    public InputControlScheme PinchSystemScheme
    {
        get
        {
            if (m_PinchSystemSchemeIndex == -1) m_PinchSystemSchemeIndex = asset.FindControlSchemeIndex("PinchSystem");
            return asset.controlSchemes[m_PinchSystemSchemeIndex];
        }
    }
    public interface IAndroidActions
    {
        void OnFirstFingerPosition(InputAction.CallbackContext context);
        void OnSecondFingerPosition(InputAction.CallbackContext context);
        void OnSecondTouchContact(InputAction.CallbackContext context);
    }
}
